server:
  port: 8764
spring:
  application:
    name: "loan"
  profiles:
    active: "qa"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: customer
    password: Root@1234
    url: jdbc:mysql://localhost:3306/customer
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate: null
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"





management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
endpoints:
  shutdown:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: "loan"
    description: "gobank loan details"
    version: "2.0.0"

logging:
  level:
    com:
      gobank:
        service: DEBUG