spring:
  application:
    name: "gatewayserver"

  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 2s

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8081/realms/master/protocol/openid-connect/certs"






management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "gobank Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      gobank:
        gatewayserver: DEBUG


resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
#server:
#  port: 8072