networks:
  gobank:
    driver: "bridge"
services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service
  accountsdb:
    container_name: account-ms
    ports:
      - 3305:3306
    environment:
      MYSQL_DATABASE: customer
    extends:
      file: common-config.yml
      service: microservice-db-config

  loandb:
    container_name: loan-ms
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: customer
    extends:
      file: common-config.yml
      service: microservice-db-config

  carddb:
    container_name: card-ms
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: customer
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "gopal159204/configserver:s10"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config



  eurekaserver:
    image: "gopal159204/eurekaserver:s10"
    container_name: eurekaserver-ms
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10

    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"




  accounts:
    image: "gopal159204/accountservice:s10"
    container_name: accounts-ms
#    ports:
#      - "8765:8765"
    healthcheck:
      test: "curl --fail --silent localhost:8765/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "account"
      SPRING_RABBITMQ_HOST: "rabbit"

      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/customer"

    extends:
      file: common-config.yml
      service: microservice-eureka-config



  loans:
    image: "gopal159204/service:s10"
    container_name: loans-ms
#    ports:
#      - "8764:8764"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8764/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10


    environment:
      SPRING_APPLICATION_NAME: "loan"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3306/customer"

    extends:
      file: common-config.yml
      service: microservice-eureka-config



  card:
    image: "gopal159204/card:s10"
    container_name: cards-ms
#    ports:
#      - "8763:8763"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8763/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10


    environment:
      SPRING_APPLICATION_NAME: "card"
      SPRING_DATASOURCE_URL: "jdbc:mysql://carddb:3306/customer"

    extends:
      file: common-config.yml
      service: microservice-eureka-config

  message:
    image: "gopal159204/message:s10"
    container_name: message-ms
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
    extends:
      file: common-config.yml
      service: network-deploy-service

  gatewaysever:
    image: "gopal159204/gatewayserver:s10"
    container_name: gatewayserver-ms
    ports:
      - "8072:8072"
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      card:
        condition: service_healthy

    environment:
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"

    extends:
      file: common-config.yml
      service: microservice-eureka-config









version: '3.8'  # Specify the version of Docker Compose syntax

#networks:
#  gobank:
#    driver: "bridge"
#
#services:
#  rabbit:
#    image: rabbitmq:3.13-management
#    hostname: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    healthcheck:
#      test: rabbitmq-diagnostics check_port_connectivity
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 5s
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: network-deploy-service
#
#  keycloak:
#    image: quay.io/keycloak/keycloak:24.0.1
#    container_name: keycloak
#    ports:
#      - "8081:8080"
#    environment:
#      KEYCLOAK_ADMIN: "admin"
#      KEYCLOAK_ADMIN_PASSWORD: "admin"
#    command: "start-dev"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: network-deploy-service
#
#  accountsdb:
#    container_name: account-ms
#    ports:
#      - 3305:3306
#    environment:
#      MYSQL_DATABASE: customer
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-db-config
#
#  loandb:
#    container_name: loan-ms
#    ports:
#      - 3307:3306
#    environment:
#      MYSQL_DATABASE: customer
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-db-config
#
#  carddb:
#    container_name: card-ms
#    ports:
#      - 3308:3306
#    environment:
#      MYSQL_DATABASE: customer
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-db-config
#
#  configserver:
#    image: "gopal159204/configserver:s9"
#    container_name: configserver-ms
#    ports:
#      - "8071:8071"
#    healthcheck:
#      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-base-config
#
#  eurekaserver:
#    image: "gopal159204/eurekaserver:s9"
#    container_name: eurekaserver-ms
#    ports:
#      - "8761:8761"
#    healthcheck:
#      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    depends_on:
#      configserver:  # Ensure configserver is healthy before starting eurekaserver
#        condition: service_healthy
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-configserver-config
#    environment:
#      SPRING_APPLICATION_NAME: "eurekaserver"
#
#  accounts:
#    image: "gopal159204/accountservice:s9"
#    container_name: accounts-ms
#    healthcheck:
#      test: "curl --fail --silent localhost:8765/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 10s
#    environment:
#      SPRING_APPLICATION_NAME: "account"
#      SPRING_RABBITMQ_HOST: "rabbit"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/customer"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-eureka-config
#
#  loans:
#    image: "gopal159204/service:s9"
#    container_name: loans-ms
#    healthcheck:
#      test: "curl --fail --silent localhost:8764/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    environment:
#      SPRING_APPLICATION_NAME: "loan"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://loandb:3306/customer"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-eureka-config
#
#  card:
#    image: "gopal159204/card:s9"
#    container_name: cards-ms
#    healthcheck:
#      test: "curl --fail --silent localhost:8763/actuator/health/readiness | grep UP || exit 1"
#      interval: 10s
#      timeout: 5s
#      retries: 10
#    environment:
#      SPRING_APPLICATION_NAME: "card"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://carddb:3306/customer"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-eureka-config
#
#  message:
#    image: "gopal159204/message:s9"
#    container_name: message-ms
#    depends_on:
#      rabbit:  # Ensure rabbit service is healthy before starting message service
#        condition: service_healthy
#    environment:
#      SPRING_RABBITMQ_HOST: "rabbit"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: network-deploy-service
#
#  gatewaysever:
#    image: "gopal159204/gatewayserver:s9"
#    container_name: gatewayserver-ms
#    ports:
#      - "8072:8072"
#    environment:
#      SPRING_APPLICATION_NAME: "gatewayserver"
#      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
#    extends:
#      file: common-config.yml  # Include common configuration from external file
#      service: microservice-eureka-config
#
